#!/usr/bin/env ruby
require 'irb'
require File.expand_path('../lib/gem-lovefest', File.dirname(__FILE__))
include GemLovefest
db_file = File.expand_path('../db/development.db', File.dirname(__FILE__))
DataMapper.setup(:default, "sqlite3://#{db_file}")
DataMapper.repository.auto_upgrade!
IRB.start
